name: Buil Package
on: [ pull_request ]
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check branch
        run: git branch
      - uses: Purushothaman22/ncc-gha@purushothaman/add-ncc-gh-action
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
