name: Delete Package
on:
 workflow_dispatch:
  inputs:
    version:
      description: 'Version of the package to be deleted'     
      required: true
jobs:
  delete-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Delete package
        uses: Purushothaman22/delete-gh-package@purushothaman/add-action
        with:
          PACKAGE_TYPE: npm
          VERSION: ${{ github.event.inputs.version }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
